# test
#Parameters:
#  InstanceType:
#    Description: Reference for the InstanceType
#    Type: String
#    Default: t2.micro
#    AllowedValues: [t2.micro]


Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0cff7528ff583bf9a
      AvailabilityZone: us-east-1a
      InstanceType: t3.micro
      SecurityGroups:
        - !Ref SSHSecurityGroup
        # EBS volume setup
      #Deletion Policy: Retain
      BlockDeviceMappings:
        - DeviceName: /dev/sdc
          Ebs:
            VolumeSize: 20
            VolumeType: gp3
            DeleteOnTermination: "true"
         #PublicKeyMaterial: String

      #SecurityGroup: !Ref xxxxxxxxxxxxx --> key in the existing security group name
      
   #take note that gp2 cannot make an 'iops' provisioned on this.

  # an elastic IP for our instance
  # MyEIP:
  #   Type: AWS::EC2::EIP
  #   Properties:
  #     InstanceId: !Ref MyInstance

  # New EC2 security group
  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to client host
      SecurityGroupIngress:
      - IpProtocol: tcp
        CidrIp: 0.0.0.0/0
        FromPort: 22
        ToPort: 22
      - IpProtocol: tcp
        CidrIp: 0.0.0.0/0
        FromPort: 3389
        ToPort: 3389
      - IpProtocol: tcp
        CidrIp: 0.0.0.0/0
        FromPort: 443
        ToPort: 443

   

Outputs:
  SGOutput:
    Description: Output for Security Group
    Value: !Ref SSHSecurityGroup
    Export:
      Name: SGoutput

      
