# test
#Parameters:
#  InstanceType:
#    Description: Reference for the InstanceType
#    Type: String
#    Default: t3.micro
#    AllowedValues: [t3.micro]
#Test 

Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0cff7528ff583bf9a
      AvailabilityZone: us-east-1d
      InstanceType: t3.micro
      EbsOptimized: false
      SecurityGroups:
        - !Ref SSHSecurityGroup
        # EBS volume setup
      #Deletion Policy: Retain
      BlockDeviceMappings:
        - DeviceName: /dev/sdc
          Ebs:
            VolumeSize: 20
            VolumeType: gp3
            DeleteOnTermination: "true"
      Tags:
        - Key: Name
          Value: CFTest
      UserData:
        Fn::Base64 !Sub |
        #!/bin/bash -xe
        sudo apt-get update
        sudo apt-get install awscli
        sudo mkdir /etc/ssl/nginx
        
   MyInstance2:
     Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0cff7528ff583bf9a
      AvailabilityZone: us-east-1b
      InstanceType: t3.micro
      EbsOptimized: false
      SecurityGroups:
        - !Ref SSHSecurityGroup
        # EBS volume setup
      #Deletion Policy: Retain
      BlockDeviceMappings:
        - DeviceName: /dev/sdc
          Ebs:
            VolumeSize: 20
            VolumeType: gp3
            DeleteOnTermination: "true"
      Tags:
        - Key: Name
          Value: Another instance 
      UserData:
        Fn::Base64 !Sub |
        #!/bin/bash -xe
        sudo apt-get update
        sudo apt-get install awscli
        sudo mkdir /etc/ssl/nginx
        sudo apt-get install mysql
        sudo apt-get install httpd
        
        
      
         #PublicKeyMaterial: String

      #SecurityGroup: !Ref xxxxxxxxxxxxx --> key in the existing security group name
      
   #take note that gp2 cannot make an 'iops' provisioned on this.

  # an elastic IP for our instance
  # MyEIP:
  #   Type: AWS::EC2::EIP
  #   Properties:
  #     InstanceId: !Ref MyInstance

  # New EC2 security group
  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to client host
      SecurityGroupIngress:
      - IpProtocol: tcp
        CidrIp: 0.0.0.0/0
        FromPort: 22
        ToPort: 22
      - IpProtocol: tcp
        CidrIp: 0.0.0.0/0
        FromPort: 3389
        ToPort: 3389
      - IpProtocol: tcp
        CidrIp: 0.0.0.0/0
        FromPort: 443
        ToPort: 443
      - IpProtocol: tcp
        CidrIp: 0.0.0.0/0
        FromPort: 80
        Toport:   80
      - IpProtocol: tcp
        CidrIp: 0.0.0.0/0
        FromPort: 3306
        Toport: 3306
   

Outputs:
  SGOutput:
    Description: Output for Security Group
    Value: !Ref SSHSecurityGroup
    Export:
      Name: SGoutput
      
  Instanceoutput:
    Description: Output for EC2 instance
    Value: !Ref Myinstance
    Export: 
      Name: InstanceOutput

      
