
Parameters:
  VpcId:
    Type: 'AWS::EC2::VPC::Id'
    Description: Choose one of the VPC 
  MaxSize:
    Type: Number
    Default: '1'
    Description: How many maximum number you can reached ?
  # InstanceType:
  #   Description: Choose your EC2 Type
  #   Type: String
  #   Default: t2.micro
  #   AllowedValues: 
  #     - t3.micro
  #     - t2.micro


Resources:
  ECSCluster:
    Type: 'AWS::ECS::Cluster'
    Properties:
      ClusterName: MyFargateCluster
      CapacityProviders:
        - FARGATE
        - FARGATE_SPOT
      DefaultCapacityProviderStrategy:
        - CapacityProvider: FARGATE
          Weight: 1
        - CapacityProvider: FARGATE_SPOT
          Weight: 1