
Resources:
  ECSCluster1:
  Type: AWS::ECS::Cluster
  Properties: 
    CapacityProviders: 
      - String
    ClusterName: ECSCF
    ClusterSettings: 
      - ClusterSettings
    Configuration: 
      ClusterConfiguration
    DefaultCapacityProviderStrategy: 
      - CapacityProviderStrategyItem
    Tags: 
      - Key: Name
        Value: ECS_Cluster
