
Parameters:

Mappings:

Resources:
  Type: AWS::ECS::Service
  Properties: 
    CapacityProviderStrategy: 
      - CapacityProviderStrategyItem
    Cluster: cluster-demo
    DeploymentConfiguration: 
      DeploymentConfiguration
    DeploymentController: 
      DeploymentController
    DesiredCount: 1
    EnableECSManagedTags: False
    EnableExecuteCommand: False
    HealthCheckGracePeriodSeconds: 30
    LaunchType: ECS
    LoadBalancers: 
      - LoadBalancer
    NetworkConfiguration: 
      NetworkConfiguration
    PlacementConstraints: 
      - PlacementConstraint
    PlacementStrategies: 
      - PlacementStrategy
    PlatformVersion: String
    PropagateTags: String
    Role: ecsInstanceRole
    SchedulingStrategy: String
    ServiceName: String
    ServiceRegistries: 
      - ServiceRegistry
    Tags: 
      - Key: Name
        Value: ECS-Demo
    TaskDefinition: String
