#It just a test 

Resources:
  newRDS:
    Type: AWS::RDS::Instance
      Properties:
        DBSecurityGroups:
        Engine: MySQL
        EngineVersion: 8.0.28
        DBInstanceIdentifier:
        MasterUsername: !Ref DBUsername
        MasterUserPassword: Hello123
        MonitoringInterval: '60'
        MonitoringRoleArn: 'arn:aws:iam::{enteryourownarn}:role/rds-monitoring-role'
        Storage:
          StorageType: IO2
