Resources:
  newRDS:
    Type: AWS::RDS::DBInstance
    Properties:
      #DBSecurityGroups: 
       # - "NewSecurityGroup"
      Engine: MySQL
      EngineVersion: 8.0.28
      DBInstanceIdentifier: "database-1"
      MasterUsername: "laputa"
      MasterUserPassword: Hello123
      #MonitoringInterval: '60'
      #MonitoringRoleArn: 'arn:aws:iam::{enteryourownarn}:role/rds-monitoring-role'
      AllocatedStorage: 20
      StorageEncrypted: False
      DBInstanceClass: db.t2.micro
      MultiAZ: False
      AvailabilityZone: us-east-1d
