Resources:
  SQSCF:
    Type: AWS::SQS::Queue
    Properties: 
      ContentBasedDeduplication: False
      DeduplicationScope: String
      DelaySeconds: 5
      FifoQueue: False
      MaximumMessageSize: 256
      MessageRetentionPeriod: 60
      QueueName: sqstest
      ReceiveMessageWaitTimeSeconds: 0
      SqsManagedSseEnabled: False
      Tags: 
        - Key: "Name"
          Value: "SQSCF"
      VisibilityTimeout: 30
