Parameters:
  appname:
    Description: The application name
  VPCId:
    Description: VPC to create the security group into
    Type: AWS::EC2::VPC::Id
  
Resources:
  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub Security group for ${appname}
      SecurityGroupIngress:
        - CidrIp: "10.0.0.0/25"